const SESSION_TOKEN_STORAGE_KEY = '@WeMovies/session-token';
const USER_DATA_STORAGE_KEY = '@WeMovies/user-data';

const AUTHORIZATION_HEADER_KEY = 'Authorization';
const BFF_API_SUBSCRIPTION_HEADER_KEY = 'Ocp-Apim-Subscription-Key';

const BFF_API_SUBSCRIPTION_KEY =
  process.env.NEXT_PUBLIC_BFF_API_SUBSCRIPTION_KEY || '';

export {
  SESSION_TOKEN_STORAGE_KEY,
  BFF_API_SUBSCRIPTION_KEY,
  AUTHORIZATION_HEADER_KEY,
  BFF_API_SUBSCRIPTION_HEADER_KEY,
  USER_DATA_STORAGE_KEY,
};
